kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: ""
  volumeName: db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
