version: '3.7'

services:

  dbdev:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dbdev
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    container_name: dbdev
    ports:
      - 5432:5432
    networks:
      - broker-kafka
    volumes:
      - /docker-volumes/postgresql/dbdev:/var/lib/postgresql/data
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  # Use localhost:9000/ to access Local Cluster
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdropLocal
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  api:
    image: homebudget-api:0.0.1
    container_name: api
    networks:
      - broker-kafka
    depends_on:
      - dbdev
    ports:
      - 8081:8081
    environment:
      DB_SERVER: dbdev
      DB_PORT: 5432

networks:
  broker-kafka:
    driver: bridge
