version: '3.7'

services:

  dbdev:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dbdev
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    container_name: dbdev
    ports:
      - 5432:5432
    volumes:
      - /docker-volumes/postgresql/dbdev:/var/lib/postgresql/data
      

networks:
  broker-kafka:
    driver: bridge
