name: Continuous Deployment Project

on:
  push:
    branches:
      - master
      - feat/ci-pipeline

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}